import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import TopNavigation from "@/components/TopNavigation/TopNavigation";
import BottomNavigation from "@/components/BottomNavigation/BottomNavigation";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${roboto.className} flex min-h-screen flex-col`}
      >
        <TopNavigation />
        <div className="flex-grow">{children}</div>
        <BottomNavigation />
      </body>
    </html>
  );
}
