import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Roboto } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import "./globals.css";
import TopNavigation from "@/components/TopNavigation/TopNavigation";
import BottomNavigation from "@/components/BottomNavigation/BottomNavigation";

import { routing } from "@/i18n/routing";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`antialiased ${roboto.className}`}>
        {/* To think - do we need top navigation on every page? */}
        <NextIntlClientProvider messages={messages}>
          <TopNavigation />
          {children}
          <BottomNavigation />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
