import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";
import TopNavigation from "@/components/TopNavigation/TopNavigation";
import BottomNavigation from "@/components/BottomNavigation/BottomNavigation";

import { isExistingLocale, routing } from "@/i18n/routing";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!isExistingLocale(locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`antialiased ${roboto.className}`}>
        {/* To think - do we need top navigation on every page? */}
        <TopNavigation />
        {children}
        <BottomNavigation />
      </body>
    </html>
  );
}

// Enable static rendering
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
